"""
Gemini API Service with Multi-Model Fallback and Resilient Alignment
Handles Google Cloud policy restrictions and payload limitations gracefully.
"""

import os
import re
import json
import base64
import ssl
import urllib.request
import urllib.error
from typing import Dict, Any, Optional, List
import certifi

# Configure SSL context for macOS
try:
    CA_FILE = certifi.where()
    os.environ["SSL_CERT_FILE"] = CA_FILE
    os.environ["REQUESTS_CA_BUNDLE"] = CA_FILE
    ssl_context = ssl.create_default_context(cafile=CA_FILE)
except Exception:
    ssl_context = ssl._create_unverified_context()

try:
    ssl._create_default_https_context = ssl._create_unverified_context
except Exception:
    pass

FALLBACK_MODELS = [
    "gemini-3.5-flash-lite",
    "gemini-3.5-flash",
    "gemini-3.6-flash",
    "gemini-3.1-flash"
]

def get_api_key(passed_key: Optional[str] = None) -> Optional[str]:
    """Resolves API key from parameter or environment."""
    if passed_key and passed_key.strip():
        return passed_key.strip()
    return os.environ.get("GEMINI_API_KEY", "").strip() or None


def call_gemini_single_attempt(prompt: str, parts: Optional[List[Dict]] = None, api_key: Optional[str] = None, model: str = "gemini-3.5-flash-lite") -> Dict[str, Any]:
    key = get_api_key(api_key)
    if not key:
        raise ValueError("GEMINI_API_KEY is not configured. Please set it in Settings.")

    url = f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent?key={key}"
    
    request_parts = list(parts) if parts else []
    request_parts.append({"text": prompt})

    payload = {
        "contents": [
            {
                "parts": request_parts
            }
        ],
        "generationConfig": {
            "responseMimeType": "application/json",
            "temperature": 0.2
        }
    }

    req_data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        url,
        data=req_data,
        headers={"Content-Type": "application/json"},
        method="POST"
    )

    with urllib.request.urlopen(req, timeout=45, context=ssl_context) as response:
        res_body = response.read().decode("utf-8")
        data = json.loads(res_body)
        
        candidates = data.get("candidates", [])
        if not candidates:
            raise ValueError("No candidate generated by Gemini.")
        
        first_candidate = candidates[0]
        content = first_candidate.get("content", {})
        c_parts = content.get("parts", [])
        if not c_parts:
            raise ValueError("Empty response parts from Gemini.")
        
        text_out = c_parts[0].get("text", "{}")
        # Clean potential markdown wrapping if present
        text_out = text_out.strip()
        if text_out.startswith("```json"):
            text_out = text_out[7:]
        if text_out.startswith("```"):
            text_out = text_out[3:]
        if text_out.endswith("```"):
            text_out = text_out[:-3]
        return json.loads(text_out.strip())


def call_gemini_resilient(prompt: str, parts: Optional[List[Dict]] = None, api_key: Optional[str] = None, preferred_model: Optional[str] = None) -> Dict[str, Any]:
    """
    Tries preferred model, then tries fallback models.
    If parts (like inline audio) causes a 403 policy or payload error,
    retries without parts using text metadata.
    """
    models_to_try = []
    if preferred_model and preferred_model.strip():
        models_to_try.append(preferred_model.strip())
    for m in FALLBACK_MODELS:
        if m not in models_to_try:
            models_to_try.append(m)

    last_error = None

    # Attempt 1: Try with audio parts across available models
    if parts:
        for m in models_to_try:
            try:
                return call_gemini_single_attempt(prompt, parts=parts, api_key=api_key, model=m)
            except urllib.error.HTTPError as e:
                err_msg = e.read().decode("utf-8", errors="ignore")
                last_error = f"Model {m} Error ({e.code}): {err_msg}"
                # If 403 policy or 413 payload too large, break to try without audio parts
                if e.code in (403, 413, 404):
                    continue
            except Exception as e:
                last_error = str(e)
                continue

    # Attempt 2: If audio payload was blocked by policy, retry with prompt text only (Title/Artist context)
    text_prompt = prompt + "\nNote: Generate synchronized lyrics and timestamps based on the song's official track structure."
    for m in models_to_try:
        try:
            return call_gemini_single_attempt(text_prompt, parts=None, api_key=api_key, model=m)
        except urllib.error.HTTPError as e:
            err_msg = e.read().decode("utf-8", errors="ignore")
            last_error = f"Model {m} Error ({e.code}): {err_msg}"
            print(f"[Gemini Notice] Model '{m}' HTTP {e.code}: {err_msg[:120]}")
            continue
        except Exception as e:
            last_error = f"Model {m} Exception: {str(e)}"
            print(f"[Gemini Notice] Model '{m}' Exception: {e}")
            continue

    if last_error and ("not allowed by policy" in str(last_error).lower() or "403" in str(last_error)):
        raise RuntimeError(
            f"Google Cloud API Key Policy Restriction (403): The Google Cloud key is restricted from calling 'generativelanguage.googleapis.com'.\n"
            f"Fix steps:\n"
            f"1. Open Google Cloud Console -> APIs & Services -> Credentials.\n"
            f"2. Edit your API Key and under 'API restrictions', choose 'Don't restrict key' OR add 'Generative Language API'.\n"
            f"3. Ensure 'Generative Language API' is enabled for your project in Google Cloud API Library.\n"
            f"Raw error detail: {last_error}"
        )

    raise RuntimeError(f"All Gemini models failed or restricted by policy. Last error: {last_error}")


def process_song_audio(audio_path: str, title: Optional[str] = None, artist: Optional[str] = None, api_key: Optional[str] = None, model: Optional[str] = None) -> Dict[str, Any]:
    """
    Processes audio or metadata using Gemini to generate timestamped lines,
    Pinyin, English translations, and word breakdown.
    """
    audio_parts = []
    file_size = os.path.getsize(audio_path) if os.path.exists(audio_path) else 0

    # Only attach inline audio if under 8MB to prevent policy payload limits
    if 0 < file_size < 8 * 1024 * 1024:
        ext = os.path.splitext(audio_path)[1].lower()
        mime_types = {
            ".mp3": "audio/mp3",
            ".wav": "audio/wav",
            ".ogg": "audio/ogg",
            ".m4a": "audio/m4a",
            ".aac": "audio/aac",
            ".webm": "audio/webm"
        }
        mime = mime_types.get(ext, "audio/mp3")
        try:
            with open(audio_path, "rb") as f:
                b64_audio = base64.b64encode(f.read()).decode("ascii")
                audio_parts.append({
                    "inlineData": {
                        "mimeType": mime,
                        "data": b64_audio
                    }
                })
        except Exception:
            audio_parts = []

    song_identifier = f"Song: '{title or 'Mandarin Song'}'"
    if artist:
        song_identifier += f" by '{artist}'"

    prompt = f"""
You are an expert Mandarin Chinese language teacher and music transcriber.
Target Song: {song_identifier}.

Provide a synchronized karaoke lyric transcript for language learners.
For each line:
1. 'startTime': timestamp in seconds (float, e.g. 14.5) when the line starts.
2. 'endTime': timestamp in seconds (float, e.g. 19.2) when the line ends.
3. 'hanzi': Chinese characters for this lyric line.
4. 'pinyin': standard Pinyin with tone marks (e.g. "nǐ wèn wǒ ài nǐ yǒu duō shēn").
5. 'english': natural English translation of this line.
6. 'words': array of segmented words/characters with:
   - 'hanzi': word in Chinese characters
   - 'pinyin': pinyin with tone marks
   - 'translation': English meaning of this word
   - 'tone': integer 1, 2, 3, 4, or 5 (neutral)
   - 'hsk': estimated HSK level (1 to 6)

Return strictly valid JSON:
{{
  "title": "{title or 'Mandarin Song'}",
  "artist": "{artist or 'Chinese Artist'}",
  "difficulty": "HSK 1-3 • Recommended",
  "languageTip": "A 1-2 sentence tip on vocabulary or pronunciation in this song",
  "lines": [
    {{
      "startTime": 0.0,
      "endTime": 4.5,
      "hanzi": "...",
      "pinyin": "...",
      "english": "...",
      "words": [
        {{
          "hanzi": "...",
          "pinyin": "...",
          "translation": "...",
          "tone": 1,
          "hsk": 1
        }}
      ]
    }}
  ]
}}
"""
    return call_gemini_resilient(prompt, parts=audio_parts, api_key=api_key, preferred_model=model)


def explain_lyric_phrase(phrase: str, line_context: str, song_title: str = "", api_key: Optional[str] = None, model: Optional[str] = None) -> Dict[str, Any]:
    """
    Queries Gemini for an in-depth breakdown of a word/phrase in song context.
    """
    prompt = f"""
You are an expert Mandarin Chinese teacher.
A student is listening to '{song_title}' and clicked on: "{phrase}".
Song line context: "{line_context}".

Provide an educational explanation for a language learner.
Return valid JSON:
{{
  "phrase": "{phrase}",
  "pinyin": "pinyin with tone accents",
  "literalMeaning": "Literal meaning of each character",
  "contextualMeaning": "Meaning and emotional nuance in this song line",
  "grammarNote": "Grammar pattern, measure word, or particle note",
  "culturalNote": "Poetic, cultural, or musical context",
  "hskLevel": "HSK 1-6",
  "exampleSentence": {{
    "hanzi": "Example sentence using this phrase",
    "pinyin": "pinyin for example sentence",
    "english": "English translation"
  }}
}}
"""
    return call_gemini_resilient(prompt, parts=None, api_key=api_key, preferred_model=model)


def translate_lyrics(lines: List[Dict[str, Any]], title: str = "", artist: str = "", api_key: Optional[str] = None, model: Optional[str] = None) -> List[Dict[str, Any]]:
    """
    Translates lyric lines into natural, poetic English using Gemini API.
    Updates each line's 'english' field with the generated translation.
    """
    if not lines:
        return lines

    key = get_api_key(api_key)
    if not key:
        raise ValueError("Gemini API key is not configured. Please add your API key in Settings.")

    # Process in batches of 40 lines to avoid token cutoffs
    batch_size = 40
    for i in range(0, len(lines), batch_size):
        chunk = lines[i:i + batch_size]
        items = [{"id": l.get("id", i + idx), "hanzi": l.get("hanzi", "")} for idx, l in enumerate(chunk)]

        song_info = f"Song: '{title}'"
        if artist:
            song_info += f" by '{artist}'"

        prompt = f"""
You are an expert Mandarin Chinese teacher and professional lyric translator.
Translate the following song lyric lines into natural, poetic, and contextually accurate English for language learners.
{song_info}

Lines to translate:
{json.dumps(items, ensure_ascii=False, indent=2)}

Return strictly a JSON array of objects with 'id' and 'english':
[
  {{
    "id": 0,
    "english": "Natural English translation of line 0"
  }}
]
"""
        response_data = call_gemini_resilient(prompt, parts=None, api_key=key, preferred_model=model)
        
        # Parse the translations from response
        translations = {}
        if isinstance(response_data, list):
            for entry in response_data:
                if isinstance(entry, dict) and "id" in entry and "english" in entry:
                    translations[str(entry["id"])] = entry["english"]
        elif isinstance(response_data, dict):
            entries = response_data.get("translations") or response_data.get("lines") or []
            if isinstance(entries, list):
                for entry in entries:
                    if isinstance(entry, dict) and "id" in entry and "english" in entry:
                        translations[str(entry["id"])] = entry["english"]
            else:
                for k, v in response_data.items():
                    if isinstance(v, str):
                        translations[str(k)] = v
                    elif isinstance(v, dict) and "english" in v:
                        translations[str(k)] = v["english"]

        # Map back to lines
        for idx, line in enumerate(chunk):
            line_id = str(line.get("id", i + idx))
            if line_id in translations and translations[line_id].strip():
                line["english"] = translations[line_id].strip()

    return lines


def extract_song_metadata_from_youtube(video_title: str, author: str = "", description: str = "", api_key: Optional[str] = None) -> Dict[str, Any]:
    """
    Uses Gemini 3.5 Flash-Lite to extract canonical track_name, artist_name, and album
    from noisy YouTube video titles and channel names for LRCLIB lyric search.
    """
    key = get_api_key(api_key)
    prompt = f"""
You are an expert in Chinese music cataloging and metadata extraction.
Given the following YouTube video information:
Title: {video_title}
Channel/Uploader: {author}
Description: {description[:300] if description else "N/A"}

Extract the canonical song title and main singer/artist in Chinese so we can search the LRCLIB lyric database.
Clean out noise like:
- "Official Music Video", "MV", "4K", "1080P", "HD", "Official Audio"
- "完整版", "動態歌詞", "Lyrics", "KTV", "字幕版"
- Episode numbers, drama names in brackets, or channel promos

Return strictly valid JSON:
{{
  "track_name": "Chinese song title, e.g. 小幸運",
  "artist_name": "Chinese artist/singer name, e.g. 田馥甄",
  "english_title": "English title if known, or empty string",
  "album_name": "Album name if known, or empty string"
}}
"""
    if key:
        try:
            data = call_gemini_resilient(prompt, parts=None, api_key=key, preferred_model="gemini-3.5-flash-lite")
            if isinstance(data, dict):
                t_name = str(data.get("track_name", "")).strip()
                a_name = str(data.get("artist_name", "")).strip()
                if t_name:
                    return {
                        "track_name": t_name,
                        "artist_name": a_name or author,
                        "english_title": str(data.get("english_title", "")).strip(),
                        "album_name": str(data.get("album_name", "")).strip()
                    }
        except Exception as e:
            print(f"Gemini YouTube metadata notice: {e}")

    # Heuristic fallback if Gemini is offline or unkeyed
    clean_title = video_title
    for tag in ["【Official MV】", "[Official MV]", "【官方MV】", "官方MV", "Official Music Video", "MV", "HD", "4K", "（歌詞版）", "【歌詞】", "歌詞", "Lyrics"]:
        clean_title = clean_title.replace(tag, "")
    clean_title = clean_title.strip(" -_[]【】()")
    parts = clean_title.split("-", 1)
    if len(parts) == 2:
        artist = parts[0].strip()
        track = parts[1].strip()
    else:
        artist = author.replace("- Topic", "").strip() if author else "Mandarin Artist"
        track = clean_title
    for tag in [
        "【Official MV】", "[Official MV]", "【官方MV】", "官方MV", "Official Music Video",
        "Official Video", "Official Audio", "MV", "HD", "4K", "1080P", "1080p",
        "（歌詞版）", "【歌詞】", "歌詞", "Lyrics", "字幕版", "動態歌詞", "KTV", "Audio", "HQ"
    ]:
        clean_title = re.sub(re.escape(tag), "", clean_title, flags=re.IGNORECASE)

    clean_title = clean_title.strip(" -_")

    def extract_chinese(text: str) -> str:
        return "".join(re.findall(r"[\u4e00-\u9fff]+", text))

    track = ""
    artist = ""
    english_title = ""

    # Known uploader/channel keywords that are not singer names
    is_author_channel = any(
        kw in (author or "").lower() for kw in [
            "topic", "records", "music", "pandarin", "channel", "video", "official",
            "唱片", "音乐", "音樂", "娱乐", "娛樂", "官方"
        ]
    )

    # 1. Check for bracket patterns: e.g. Artist【Title】or Title【Artist】
    bracket_m = re.search(r"[【《\[\(](.*?)(?:[】》\]\)]|$)", clean_title)
    if bracket_m:
        inside = bracket_m.group(1).strip()
        outside = re.sub(r"[【《\[\(].*?(?:[】》\]\)]|$)", " ", clean_title).strip(" -_")
        
        inside_zh = extract_chinese(inside)
        outside_zh = extract_chinese(outside)

        if inside_zh and outside_zh:
            # Usually outside is Artist and inside is Track (e.g. Michael Wong 光良【 Fairy Tale 童话 Tong Hua 】)
            track = inside_zh
            artist = outside_zh
            eng_words = re.findall(r"[A-Za-z]+(?:\s+[A-Za-z]+)*", inside)
            if eng_words:
                english_title = eng_words[0].strip()
        elif inside_zh:
            track = inside_zh
            artist = outside_zh or (author if not is_author_channel else "Mandarin Artist")
        elif outside_zh:
            track = outside_zh
            artist = inside or (author if not is_author_channel else "Mandarin Artist")
        else:
            track = inside or outside
            artist = outside if inside else (author if not is_author_channel else "Mandarin Artist")

    # 2. Check for dash split: Artist - Track or Track - Artist
    if not track and (" - " in clean_title or "-" in clean_title):
        parts = [p.strip() for p in re.split(r"\s*-\s*", clean_title) if p.strip()]
        if len(parts) >= 2:
            p0, p1 = parts[0], parts[1]
            p0_zh = extract_chinese(p0)
            p1_zh = extract_chinese(p1)
            if p0_zh and p1_zh:
                artist = p0_zh
                track = p1_zh
            else:
                artist = p0
                track = p1

    # 3. Fallback to full cleaned title and author
    if not track:
        zh_title = extract_chinese(clean_title)
        track = zh_title if zh_title else clean_title.strip(" -_[]【】()")
        artist = extract_chinese(author) or (author if not is_author_channel else "")
        if not artist:
            artist = "Mandarin Artist"

    return {
        "track_name": track,
        "artist_name": artist,
        "english_title": "",
        "english_title": english_title,
        "album_name": ""
    }
